name = "birthdayrsvp"
compatibility_date = "2023-01-01"

[site]
bucket = "./public"

[[d1_databases]]
binding = "DB"
database_name = "birthdayrsvp"
database_id = "YOUR_DATABASE_ID_HERE"

[build]
command = ""
[build.upload]
format = "service-worker"